import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SideBar } from "@/components/sidebar";
import PageWrapper from "@/components/pagewrapper";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + "h-screen overflow-hidden"}>
      <SideBar />
        <div className="flex flex-col h-full w-full">
          <Header />
          <PageWrapper children={children} />
        </div>
      </body>
    </html>
  );
}
